### ISSUE TITLE
Annotated configuration for data sources

### ISSUE THREAD

**Issue by TobiasHauck** [CircleOfNice/DoctrineRestDriver#33]
#### What is this feature about (expected vs actual behaviour)?
I want to define another configuration for a datasource than the global config of the driver. Twitter for instance uses HTTP POST for deleting items which is not possible to configure yet.

#### How can I reproduce it?
Try to find a way to change the http method for a datasource - it isn't possible yet

#### Does it take minutes, hours or days to fix?
days

#### Any additional information?

**Comment by TobiasHauck** [comment]
Actually the annotation looks like this:
```
@DataSource\Select("http://127.0.0.1:3000/mockapi/products")
```

What should be configurable in my opinion is:
- URL (already done)
- HTTP method
- Valid status codes
- Payload format
- Auth strategy

So what I'd suggest is to change the API of the annotations like this:
```
@DataSource\Select(
    url="http://127.0.0.1:3000/mockapi/products",
    httpMethod="POST",
    statusCodes=[200, 201],
    format="xml",
    auth="HttpAuthentication"
)
```

@donjuandem what do you think about this idea?

**Comment by donjuandem** [comment]
i don't know how this notation's supposed to work, because as far as my knowledge goes, php does not yet (if ever) support named function arguments, so it has to be either...

```php
@DataSource\Select(
    "http://127.0.0.1:3000/mockapi/products",
    "POST",
    [200, 201],
    "xml",
    "HttpAuthentication"
)
```

which is a very bad way to add the options, since i have to call the annotation always with all parameters coming before the option i want to change (example)...

```js
@DataSource\Select(
    "http://127.0.0.1:3000/mockapi/products",
    null,
    null,
    null,
    "HttpAuthentication"
)
```

which i think is an utterly crappy solution. The other way I see is using a hashmap for everything...

```php
@DataSource\Select([
    url => "http://127.0.0.1:3000/mockapi/products",
    httpMethod => "POST",
    statusCodes => [200, 201],
    format => "xml",
    auth => "HttpAuthentication"
])
```

so that the bad example from above turns into this one:

```php
@DataSource\Select([
    url => "http://127.0.0.1:3000/mockapi/products",
    auth => "HttpAuthentication"
])
```

But I'm not convinced of this one either because for some standard usecases this options seem to get kind of verbose:

```php
@DataSource\Select([
    url                => "http://127.0.0.1:3000/mockapi/products",
    httpMethod => "POST",
    auth             => "HttpAuthentication"
])
@DataSource\Fetch([
    url => "http://127.0.0.1:3000/mockapi/products",
    auth => "HttpAuthentication"
])
@DataSource\Insert([
    url => "http://127.0.0.1:3000/mockapi/products",
    auth => "HttpAuthentication"
])
class X {}
```

If we look at the options, i think it is clear, that for example the auth strategy should not really change with each route (of course it could but i don't think it's a good idea to make concessions, which harm valid use cases and instead supporting insane use cases). The way I would like to write down this one would be:


```php
@DataSource([
    auth: "HttpAuthentication"
])
@DataSource\Select("http://127.0.0.1:3000/mockapi/products", [
    method => "POST",
])
@DataSource\Fetch("http://127.0.0.1:3000/mockapi/products")
@DataSource\Insert("http://127.0.0.1:3000/mockapi/products")
class X {}
```

So by analyzing this, it's clear, that it should be possible to configure options that overwrite the defaults on every route (@DataSource annotation) because things like auth strategy and format usually don't change with the routes on the same datasource. Taking it a step further, the three things that usually change with routes are: URL, successCode and method. If we assume the following: Anyone who wants configure a success code, wants to configure the url and method, too and anyone who wants to configure the method, needs to configure the url, too, the most useful solution respecting on the one hand all "normal" use cases and on the other hand the weird ones would be:

```php
@DataSource([
    auth:     "HttpAuthentication"
    format: "xml"
])
@DataSource\Select("http://127.0.0.1:3000/mockapi/products")
@DataSource\Fetch("http://127.0.0.1:3000/mockapi/products", "POST")
@DataSource\Insert("http://127.0.0.1:3000/mockapi/products", "POST", 201, [
   // all weird options possible - possibly making the user able to use plain restdriver/curl options
])
class X {}
```

**Comment by TobiasHauck** [comment]
The Doctrine annotation reader and the PHP platform don't support a few of your final suggestions which I'm generally fine with:

You can't use a namespace alias twice, which would be necessary to support ```@DataSource``` and ```@DataSource\...```. I'd suggest to rename the DataSource annotation with "Config", so that we could write ```@DataSource\Config([...]).

Second problem: To use hashmaps in annotations you need to write down the annotation like this:
```
@DataSource(
    auth = "HttpAuthentication"
    format = "xml"
)
```
which is very ugly. I've tried a few other things, but all of them failed.

The same problem goes with list declarations in annotations: It isn't possible at all. So we need to use the same ugly notations than before:
```
@DataSource\Select(
    url = "http://127.0.0.1:3000/mockapi/products",
    method = "POST",
    statusCode = 201,
    options = [...]
)
```

So after all these changes we are nearly at my first suggestion.

To realize the suggested notation I had to write another annotation reader which is basically possible.

**Comment by TobiasHauck** [comment]
My opinion is that it's pretty ugly to use the annotations this way:

```php
@DataSource(
    auth   = "HttpAuthentication"
    format = "xml"
)
@DataSource\Select(
    url        = "http://127.0.0.1:3000/mockapi/products",
    method     = "POST",
    statusCode = 201,
    options    = [...]
)
class X {}
```

but besides looking ugly it's very clear to understand what's going on. I know we don't wanna produce any shit - do you think it is?
